name: BuyerAssistBot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  notify-pr-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Post Slack messages
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: abinoda/slack-action@v1.0.7
      with:
        args: '{\"channel\":\"C032NCAKJPR\",\"text\":\"Hello world\"}'
    
