name: BuyerAssistBot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  notify-pr-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Notify PR changes
        uses: GoldenspearLLC/slack-chat-postmessage@v3
        with:
          channel: '#response'
          text: "GITHUB::${{ github.event_name }} -- https://github.com/example/repo#${{ github.head_ref }}"
    
