name: BuyerAssistBot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Post to a Slack channel
      id: slack
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: deployments
        payload: >-
          {
            "icon_emoji": ":rocket:",
            "username": "Deployer",
            "attachments": [
              {
                "author_name": "${{ github.event.sender.login }}",
                "author_link": "${{ github.event.sender.html_url }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "color": "good",
                "fallback": "Deployment finished.",
                "pretext": "Deployment finished.",
                "fields": [
                    {
                      "title": "Revision",
                      "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}@${{ github.ref }}>",
                      "short": true
                    }
                ],
                "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}>",
              }
            ]
          }
    