name: BuyerAssistBot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send Slack Message
      uses: parkingboss/slackbot-postmessage@v1
      with:
        token: ${{ secrets.SLACK_BOT_TOKEN }}
        request: '{\"channel\":\"C032NCAKJPR\",\"text\":\"Wrok\"}'
    
